version: '3.8'

services:
  mydb:
    build:
      context: ./mydb
    image: my-mariadb
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dockercompose-frontend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 15s
      retries: 5

  frontend:
    build:
      context: ./frontend
    image: custom-phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    depends_on:
      mydb:
        condition: service_healthy
    networks:
      - dockercompose-frontend

volumes:
  mysql_data:

networks:
  dockercompose-frontend:
